apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-100301-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/chatbot-100301/overlays/development
    repoURL: https://github.com/fpetk/chatbot-100301-gitops.git
    targetRevision: main
  destination:
    namespace: ai-software-templates-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
