kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chatbot-100301-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: chatbot-100301-dsp-job
    namespace: ai-software-templates-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chatbot-100301-imagestream-job-role
