apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: chatbot-100301
  janus-idp.io/tekton: chatbot-100301
  backstage.io/kubernetes-id: chatbot-100301
  backstage.io/kubernetes-namespace: ai-software-templates-dev
  app.kubernetes.io/part-of: chatbot-100301
resources:
  - initialize-namespace.yaml
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
  - rhoai/
