apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-100301
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-100301
  name: chatbot-100301
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
