apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chatbot-100301
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-100301
  name: chatbot-100301
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot-100301
